### ISSUE TITLE
Add support to send email / sms

### ISSUE THREAD

**Issue by StefanoMartin** [Wappsto/javascript-wappsto-wapp#107]
Add support to send email and sms.

To send email you can use:
POST /services/2.0/email_send
```json
{
      "html": "<h1>Ciao</h1>",
       "subject": "HI!!!",
       "from": "My friendly hello app"
 }
```

If successful, a httpresponse with code 482_000_001 will be returned.

To send sms you can use:
POST /services/2.0/sms_send
```json
{
     "content": "Ciao"
 }
```

If successful, a httpresponse with code 482_000_001 will be returned.

**Comment by AndreasBomholtz** [comment]
Added in version v0.12.2
