### ISSUE TITLE
Add filtered period

### ISSUE THREAD

**Issue by StefanoMartin** [Wappsto/javascript-wappsto-wapp#195]
When you use delta, the API will not modify the data if the data did not overcome a certain delta value.

I will expect something similar for "period". 
If I set ```value.setReport("5")``` with period "10" but the 10 seconds have been not passed from the last update then setReport should not update the value. 

I also would like to have a "force" command to force the update the Report even if "delta" or "period" are not satisfied. This could be useful if the user wants to trigger a forced refresh of the values without removing delta and period.

**Comment by AndreasBomholtz** [comment]
@StefanoMartin It is possible to create this behavior by setting delta to a very big number (Inf) then, only the value at the period will be send.
