### ISSUE TITLE
Support historical

### ISSUE THREAD

**Issue by AndreasBomholtz** [Wappsto/javascript-wappsto-wapp#5]
It should be possible to load historical:
* geo
* state
* connection

**Comment by StefanoMartin** [comment]
In Historical for state this option should be possible:
* operation (in bold the most important): 
        * "arbitrary": fetch a random element 
        * "array_agg": return array of data 
        * "**mean**": average of data
        * "**count**": amount of data
        * "geometric_mean": geometric mean
        * "**max**": maximum 
        * "**min**": minimum 
        * "stddev": standard deviation
        * "**sum**": sum of data
        * "**variance**": variance 
        * "harmonic_mean": harmonic mean
        * "first": first element 
        * "last": last element
        * "count_distinct": count distinc values
        * "lower_quartile": 25% percentile
        * "median": median (50% percentile)
        * "upper_quartile": 75% percentile
        * "mode": mode
 * group_by:
       * "year"
       * "quarter": every 3 months
       * "month"
       * "week"
       * "day"
       * "hour"
       * "minute",
       * "second"
       * "millisecond"
    
Other possible options are:
* timestamp_format: to return in different format than ISO (in [moment() format](https://momentjs.com/docs/#/displaying/format/)) 
* timezone: to return in a different timezone format than ISO (but maybe moment() already support it during parsing)
* order: "ascending" and "descending" options
