### ISSUE TITLE
Template value BOOLEAN_ONOFF does not work

### ISSUE THREAD

**Issue by tsvetomir-ivanov** [Wappsto/javascript-wappsto-wapp#58]
I get the error message `You cannot add mapping and meaningful zero in the same body`.
I am interested in keeping the mapping and removing the meaningful zero attribute, in case it is not allowed.

It appears that the list of controlled value types has been updated to reflect that change. It may be time to release it.

**Comment by AndreasBomholtz** [comment]
Fixed by updating the templates.
