### ISSUE TITLE
value.onRefresh() not working after first time it is called

### ISSUE THREAD

**Issue by tsvetomir-ivanov** [Wappsto/javascript-wappsto-wapp#60]
I have a number value, which was created as follows
```js
let val = await device.createNumberValue({
    name: 'Total energy',
    permission: 'r',
    type: 'energy',
    min: 0,
    max: 11500,
    step: 0.01,
    unit: 'Wh',
    delta: '50',
    period: '5m'
});
```
Then, I added onRefresh callback as follows
```js
val.onRefresh((value) => {
    value.report(value.last_data);
});
```
The problem I observe is that I can trigger this callback only once via the Wappsto dashboard's `Get device latest data` button. All subsequent requests are successful, but no callback is triggered in my program.

Note that the same behavior is present if the `onRefresh` callback is called by the lib (e.g. due to the period settings). However, subsequent `onRefresh` calls are there due to the period settings.

**Comment by AndreasBomholtz** [comment]
I have added a small fix, but the main issue is in the backend. It do not send the event on the stream when the status is already "update". To trigger the update event, you first have to clear the status by sending `"status: null` to clear it.
